### ISSUE TITLE
Touch of Class book site link for downloading Traffic software

### ISSUE THREAD

**Issue by ThomasGoering** [eiffelhub/Traffic3#3]
The book Touch of Class mentions at least two web pages (see page 15):

To download Traffic: traffic.origo.ethz.ch
Book site: touch.ethz.ch

The first link doesn't work anymore. If possible, it should be "reactivated".

The book site is still available but links to the Traffic4 project (https://bitbucket.org/nadiapolikarpova/traffic/wiki/Home). But this project is not usable for book readers as it doesn't contain the example mentioned in the different chapters of the book.

Instead, this site should link to this Traffic3 project to allow book readers nowadays to work with the book as intended (and possible) in the past.

**Comment by jvelilla** [comment]
Hi Thomas 
> 
> The book Touch of Class mentions at least two web pages (see page 15):
> 
> To download Traffic: traffic.origo.ethz.ch
> Book site: touch.ethz.ch
> 
> The first link doesn't work anymore. If possible, it should be "reactivated".
>
Unfortunately Origo closed end of May 2012. 
> The book site is still available but links to the Traffic4 project (https://bitbucket.org/nadiapolikarpova/traffic/wiki/Home). But this project is not usable for book readers as it doesn't contain the example mentioned in the different chapters of the book.
> 
> Instead, this site should link to this Traffic3 project to allow book readers nowadays to work with the book as intended (and possible) in the past.

The site will be updated soon, thanks.

**Comment by ThomasGoering** [comment]
> Hi Thomas
> 
> > The book Touch of Class mentions at least two web pages (see page 15):
> > To download Traffic: traffic.origo.ethz.ch
> > Book site: touch.ethz.ch
> > The first link doesn't work anymore. If possible, it should be "reactivated".
> 
> Unfortunately Origo closed end of May 2012.

Is there an archive of Origo available anywhere?

> > The book site is still available but links to the Traffic4 project (https://bitbucket.org/nadiapolikarpova/traffic/wiki/Home). But this project is not usable for book readers as it doesn't contain the example mentioned in the different chapters of the book.
> > Instead, this site should link to this Traffic3 project to allow book readers nowadays to work with the book as intended (and possible) in the past.
> 
> The site will be updated soon, thanks.

Thanks, so we can close this issue as soon as the book site is updated.

**Comment by ThomasGoering** [comment]
Book site was updated. It now links to this Github project.
