### ISSUE TITLE
Examples do not correspond to what is printed in the book Touch of Class

### ISSUE THREAD

**Issue by ThomasGoering** [eiffelhub/Traffic3#4]
The Traffic examples differ from what is printed in the book Touch of Class (at least in the 1st printing from 2009).

The code excerpts printed in the book suggest that the examples in the downloadable Traffic software is not complete and should be extended by the reader.
But in most cases they already contain „a possible“ final result of what the reader is supposed do. 

This could confuse book readers, especially less experienced ones.

In the following there is a list of differences in the book and the projects in the examples folder.

**Chapter 2**
On page 16, feature _explore_ of class _PREVIEW_ has an empty line between **do** and **end**. But the same feature of this class in folder examples/02_objects of the Traffic project already contains „The text you should type in“ (see page 18 of the book) and an additional line.

**Chapter 4**
On page 56, feature _tryout_ of class _QUERIES_AND_COMMANDS_ is empty as well. The same feature of this class in folder exampled/04_interfaces is also not empty, although it differs more from what the book readers is supposed to fill in as described on page 61.

**Chapter 6**
Similar, but also different: See page 108, which states „Bring up the class of interest for the present discussion, _LINE_BUILDING_, which initially looks like this:“ The same feature of this class in folder examples/06_creation is also different. This time the book prints more than one „evolutions“ of this feature, but this time it also says on page 125: „Since all this is available as part of the predefined examples, it is a good idea to go and read its final form:“ This time it seems that the example is already final and includes everything what the reader should have been tried out.

**Chapter 7**
Page 154 doesn’t print the whole definition of feature _traverse_ of class _ROUTES_. But also here does the feature of this class in folder examples/07_control contains a more advanced loop (including e.g. variant and invariant that are introduced throughout this chapter). Again, it differs from what is printed in the book on page 180 and later also used in chapter 8.

**Chapter 8**
Here, an evolution of the excerpt from page 180 is repeated and extended. Class _ROUTES_ in folder examples/08_routines in this case also contains the final version.

**Chapter 9**
Until now I haven’t looked more deeply into the chapter and the content in folder examples/09_variables.

Also I haven’t yet looked more deeply into the content in folders examples/assignment_9 and examples/city_vision2 to which parts of the book the belong to.

As I don’t know the initial intention what should be in the Traffic software, that the book readers are supposed to download and work on, I’m not sure about how it should be changed or if this should be changed at all. But as already said: Book readers could be confused when they download and work on the examples as they appear in the book.

Hopefully a discussion on this leads to a final decision. And if the examples should be adapted, additional issues for each chapter could be created.

**Comment by jvelilla** [comment]
Ok, I see, we can rename the current examples folder as solutions and build a new examples folder.

**Comment by ThomasGoering** [comment]
Good idea to provide the solutions (or "predefined examples" as one can think of them; this would also match the sentence "Since all this is available as part of the predefined examples, ..." on page 125, last paragraph) and still the (empty) examples that can be used to work on with the book. Nothing gets lost and the examples can be adapted to match the book.

I did this in my local fork up to chapter 9. The solution folder is the exact copy of the original example folder. The classes mentioned in the book of each example project are stripped-down (and unified) to provide a starting point when working with the book.

You can find it at https://github.com/ThomasGoering/Traffic3/tree/example-update.
@jvelilla: Please let me know your feedback.

Note, that I also updated two text files to match the new directory structure and the history.

BTW: File developer.txt mentions a folder doc, which I cannot find and don't know its original content. If you don't mind I could remove it from file developer.txt.

**Comment by ThomasGoering** [comment]
@jvelilla I created pull request #6 with the changes mentioned above (including the change in developer.txt). It also includes a version update to 3.4 (see also history.txt).

**Comment by jvelilla** [comment]
@ThomasGoering  thanks for your contribution, I've merged it.
